# Generated by Django 4.2.19 on 2025-02-27 05:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ma'lumot yo'nalishlari", max_length=100, verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name_plural': "Yo'nalishlar",
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Kontak')),
                ('email', models.EmailField(max_length=300, verbose_name='Email')),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-update_time'], 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='nomi',
        ),
        migrations.RemoveField(
            model_name='news',
            name='rasmi',
        ),
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.TextField(default='sdfasdf', verbose_name='Asosiy qismi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-25 12:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='media/news/about-img.png', upload_to='news/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='pulish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.CharField(default='slugtest', help_text="O'zi-ozini to'ldiradi", max_length=250, verbose_name='Url shakli'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PD', 'Published')], default='DF', max_length=2),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='sdfsdfsdfsd', help_text='Title of the news', max_length=250, verbose_name='Xabar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),

    ]
