# Generated by Django 4.2.19 on 2025-02-27 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0002_category_contact_alter_news_options_remove_news_nomi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baza.category'),
            preserve_default=False,
        ),
    ]
